// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** The ChatParticipant model. */
@Fluent
public final class ChatParticipant {
    /*
     * The id of the chat participant.
     */
    @JsonProperty(value = "id", required = true)
    private String id;

    /*
     * Display name for the chat participant.
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /*
     * Time from which the chat history is shared with the participant. The
<<<<<<< HEAD:sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/implementation/models/ChatParticipant.java
     * timestamp is in ISO8601 format: `yyyy-MM-ddTHH:mm:ssZ`.
=======
     * timestamp is in RFC3339 format: `yyyy-MM-ddTHH:mm:ssZ`.
>>>>>>> 3607e737b627a7840215e6eca6be23ee44780441:sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/implementation/models/ChatThreadMember.java
     */
    @JsonProperty(value = "shareHistoryTime", required = true)
    private OffsetDateTime shareHistoryTime;

    /**
     * Get the id property: The id of the chat participant.
     *
     * @return the id value.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Set the id property: The id of the chat participant.
     *
     * @param id the id value to set.
     * @return the ChatParticipant object itself.
     */
    public ChatParticipant setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the displayName property: Display name for the chat participant.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Set the displayName property: Display name for the chat participant.
     *
     * @param displayName the displayName value to set.
     * @return the ChatParticipant object itself.
     */
    public ChatParticipant setDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * Get the shareHistoryTime property: Time from which the chat history is shared with the participant. The timestamp
<<<<<<< HEAD:sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/implementation/models/ChatParticipant.java
     * is in ISO8601 format: `yyyy-MM-ddTHH:mm:ssZ`.
=======
     * is in RFC3339 format: `yyyy-MM-ddTHH:mm:ssZ`.
>>>>>>> 3607e737b627a7840215e6eca6be23ee44780441:sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/implementation/models/ChatThreadMember.java
     *
     * @return the shareHistoryTime value.
     */
    public OffsetDateTime getShareHistoryTime() {
        return this.shareHistoryTime;
    }

    /**
     * Set the shareHistoryTime property: Time from which the chat history is shared with the participant. The timestamp
<<<<<<< HEAD:sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/implementation/models/ChatParticipant.java
     * is in ISO8601 format: `yyyy-MM-ddTHH:mm:ssZ`.
=======
     * is in RFC3339 format: `yyyy-MM-ddTHH:mm:ssZ`.
>>>>>>> 3607e737b627a7840215e6eca6be23ee44780441:sdk/communication/azure-communication-chat/src/main/java/com/azure/communication/chat/implementation/models/ChatThreadMember.java
     *
     * @param shareHistoryTime the shareHistoryTime value to set.
     * @return the ChatParticipant object itself.
     */
    public ChatParticipant setShareHistoryTime(OffsetDateTime shareHistoryTime) {
        this.shareHistoryTime = shareHistoryTime;
        return this;
    }
}
