// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.chat.implementation.models;

import com.azure.communication.chat.models.CreateChatThreadErrors;
import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The CreateChatThreadResult model. */
@Fluent
public final class CreateChatThreadResult {
    /*
<<<<<<< HEAD
     * The thread property.
     */
    @JsonProperty(value = "thread")
    private ChatThread thread;

    /*
     * The errors property.
=======
     * Chat thread.
     */
    @JsonProperty(value = "chatThread")
    private ChatThread chatThread;

    /*
     * Errors encountered during the creation of the chat thread.
>>>>>>> 3607e737b627a7840215e6eca6be23ee44780441
     */
    @JsonProperty(value = "errors")
    private CreateChatThreadErrors errors;

    /**
<<<<<<< HEAD
     * Get the thread property: The thread property.
     *
     * @return the thread value.
     */
    public ChatThread getThread() {
        return this.thread;
    }

    /**
     * Set the thread property: The thread property.
     *
     * @param thread the thread value to set.
     * @return the CreateChatThreadResult object itself.
     */
    public CreateChatThreadResult setThread(ChatThread thread) {
        this.thread = thread;
=======
     * Get the chatThread property: Chat thread.
     *
     * @return the chatThread value.
     */
    public ChatThread getChatThread() {
        return this.chatThread;
    }

    /**
     * Set the chatThread property: Chat thread.
     *
     * @param chatThread the chatThread value to set.
     * @return the CreateChatThreadResult object itself.
     */
    public CreateChatThreadResult setChatThread(ChatThread chatThread) {
        this.chatThread = chatThread;
>>>>>>> 3607e737b627a7840215e6eca6be23ee44780441
        return this;
    }

    /**
<<<<<<< HEAD
     * Get the errors property: The errors property.
=======
     * Get the errors property: Errors encountered during the creation of the chat thread.
>>>>>>> 3607e737b627a7840215e6eca6be23ee44780441
     *
     * @return the errors value.
     */
    public CreateChatThreadErrors getErrors() {
        return this.errors;
    }

    /**
<<<<<<< HEAD
     * Set the errors property: The errors property.
=======
     * Set the errors property: Errors encountered during the creation of the chat thread.
>>>>>>> 3607e737b627a7840215e6eca6be23ee44780441
     *
     * @param errors the errors value to set.
     * @return the CreateChatThreadResult object itself.
     */
    public CreateChatThreadResult setErrors(CreateChatThreadErrors errors) {
        this.errors = errors;
        return this;
    }
}
